import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FiMail, FiPhone, FiMap, FiFacebook, FiTwitter, FiGithub, FiYoutube } from 'react-icons/fi';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Contact Us</h1>
      <p className="sub-title">Any questiopn or remarks? Just write us a message!</p>
      <div id="contact-container">
        <div className="contact-info">
          <h4>Contact information</h4>
          <p>fill up the form and then click send</p>
          <div className="icon-text">
            <FiPhone className="contact-icon"/>
            <span> +7-927-850-09-16</span>
          </div>
          <div className="icon-text">
            <FiMail  className="contact-icon"/>
            <span>it@for-all.world</span>
          </div>
          <div className="icon-text">
            <FiMap  className="contact-icon"/>
            <span>Milky way galaxy, Sun solar system, Earth planet</span>
          </div>
          <div className="social-media">
            <a href="#" className="icon-circle">
              <FiFacebook className="social-icon"/>
            </a>
            <a href="#" className="icon-circle">
              <FiTwitter  className="social-icon"/>
            </a>
            <a href="#" className="icon-circle">
              <FiGithub  className="social-icon"/>
            </a>
            <a href="#" className="icon-circle">
              <FiYoutube  className="social-icon"/>
            </a>
          </div>
        </div>
        <form>
          <div className="col">
            <div className="form-group">
              <label>First Name</label>
              <input type="text" />
            </div>
            <div className="form-group">
              <label>Last Name</label>
              <input type="text" />
            </div>
          </div>
          <div className="col">
            <div className="form-group">
              <label>E-Mail</label>
              <input type="email" />
            </div>
            <div className="form-group">
              <label>Phone #</label>
              <input type="tel" />
            </div>
          </div>
          <div className="col">
            <div className="form-group">
              <label>What Type Of Website Do You Need?</label>
              <div className="radio-buttons">
                <div className="radio-btn">
                  <input type="radio" id="radiopersonal" name="type" value="personal"/>
                  <label for="radiopersonal">Personal</label>
                </div>
                <div className="radio-btn">
                  <input type="radio" id="radioecommerce" name="type" value="ecommerce"/>
                  <label for="radioecommerce">E-commerce</label>
                </div>
                <div className="radio-btn">
                  <input type="radio" id="radiolandingpage" name="type" value="landingpage"/>
                  <label for="radiolandingpage">Landing Page</label>
                </div>
              </div>
            </div>
          </div>
          <div className="col">
            <div className="solo">
              <label>Message</label>
              <textarea></textarea>
            </div>
          </div>
          <div className="col">
            <div className="solo right">
              <button className="primary">Send Message</button>
            </div>
          </div>
        </form>
      </div>
    </>
  )
}
